name: linter
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          pip install poetry flake8 pytest
          make install
      - run: make build
      - run: python3 -m pip install --upgrade pip
      - run: python3 -m pip install --force dist/*.whl
      - run: python3 -m pip install flake8
      - run: make lint
