name: linter
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: install dependencies
        run: |
          pip install poetry flake8 pytest
          make install
      - name: build
        run: make build
      - name: upgrade pip
        run: python3 -m pip install --upgrade pip
      - name: package-install
        run: python3 -m pip install --force dist/*.whl
      - name: make lint
        run: make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
