name: linter
on: push
env:
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: install dependencies
        run: |
          pip install poetry flake8 pytest
          make install
      - name: build
        run: make build
      - name: upgrade pip
        run: python3 -m pip install --upgrade pip
      - name: package-install
        run: python3 -m pip install --force dist/*.whl
      - name: make lint
        run: make lint
      - name: Run test
        run: make test
      - name: pytest-cov
        run: make pytest-cov
      - name: test coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: d4487df68bc74f878059cad0940fc6807db028824ce4deec41d76d16e835da4a
        with:
          coverageCommand: make test-coverage
          debug: true
