name: make-lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          pip install poetry flake8 pytest
          make install
      - run: make build
      - run: python3 -m pip install --upgrade pip
      - run: python3 -m pip install --force dist/*.whl
      - run: python3 -m pip install flake8
      - run: python3 -m pip install pytest-cov
      - run: make lint
      - run: make test
      - run: make pytest-cov
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMAT_PROJECT_50 }}
        with:
          coverageCommand: make test-coverage
          debug: true
